name: test branch

on:
  workflow_dispatch:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  rotate:
    name: rotate iam user keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: rotate aws keys
        id: testRotation
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.validate_access_key_name }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.validate_secret_key_name }}
          IAM_USERNAME: ${{ secrets.validate_username}}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          OWNER_REPOSITORY: ${{ github.repository }}
          GITHUB_ACCESS_KEY_NAME: validate_access_key_name
          GITHUB_SECRET_KEY_NAME: validate_secret_key_name

  rollback:
    if: ${{ failure() && needs.rotate.result=='failure'}}
    name: rollback keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Rollback Keys
        if: steps.testRotation.outcome == 'failure'
        run: |
          pushd ./action_files
          python reset_ci.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.recovery_access_key_name }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.recovery_secret_key_name }}
          IAM_USERNAME: ${{ secrets.validate_username}}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          OWNER_REPOSITORY: ${{ github.repository }}
          GITHUB_ACCESS_KEY_NAME: validate_access_key_name
          GITHUB_SECRET_KEY_NAME: validate_secret_key_name

      - name: Send Slack Status
        uses: 8398a7/action-slack@45986a1c69e93353648c176ce49eecddebebf64e # Commit sha v3.9.0
        with:
          status: ${{job.status}}
          author_name: ${{ secrets.recovery_username}}
          username: ${{ secrets.recovery_username}}
          text: Branch Test Failed. Rollback ran in ${{ github.run_id }} for ${{ secrets.validate_username}} in gihub-action-rotate-aws-secrets
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_ADDRESS }}
