name: validate master

on:
  workflow_dispatch:

jobs:
  rotate:
    name: rotate iam user keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: rotate aws keys
        uses: kneemaa/github-action-rotate-aws-secrets@v1.1.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.validate_access_key_name }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.validate_secret_key_name }}
          IAM_USERNAME: ${{ secrets.validate_username}}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          OWNER_REPOSITORY: ${{ github.repository }}
          GITHUB_ACCESS_KEY_NAME: validate_access_key_name
          GITHUB_SECRET_KEY_NAME: validate_secret_key_name
